### ISSUE TITLE
Tomato app to tested applications

### ISSUE THREAD

**Issue by kirsik** [Sensotrend/nightscout-fi#192]
Tomato app http://tomato.cool/ has been tested by a user to work with Nightscout Connect.

Add the app to the list of tested applications in the instructions.

**Comment by HannuHyttinen** [comment]
Verification has been done by beta-group.

Verification results:
- [x] Pass. According the [test results](https://github.com/Sensotrend/sensotrend-regulatory/blob/master/product-sensotrend-connect/alpha-beta-testing/Nightscout%20Connect%20-%20Yhteensopivuustestaus%20-%20Tomato.pdf), data transfer from Tomato to Kanta PHR via Nightscout Connect has worked without problems. No errors or hazards were detected.
